version: "3.8"

services:
  db:
    image: mysql:8
    container_name: merchex-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: listings
      MYSQL_USER: merchex
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - merchex_net

  web:
    build: .
    container_name: merchex-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: merchex.settings_nas
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: listings
      MYSQL_USER: merchex
      MYSQL_PASSWORD: password

      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@egliseevangeliqueparis12.org
      DJANGO_SUPERUSER_PASSWORD: "CHANGE_ME_STRONG_PASSWORD"
    networks:
      - merchex_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: merchex-phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: merchex
      PMA_PASSWORD: password
    ports:
      - "8082:80"
    networks:
      - merchex_net

volumes:
  mysql_data:

networks:
  merchex_net:
