version: "3.8"

services:
  db:
    image: mysql:8
    container_name: merchex-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: merchex
      MYSQL_USER: merchex
      MYSQL_PASSWORD: password
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: merchex-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8002:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: merchex.settings_nas
      MYSQL_HOST: db
      MYSQL_DATABASE: merchex
      MYSQL_USER: merchex
      MYSQL_PASSWORD: password

volumes:
  mysql_data:
